preview = true      # 启用预览模式
line-length = 120   # 设置一行最大长度
indent-width = 4    # tab每次缩进所用的空格数

# 选择要检查的规则
select = [
    "B",     # Bug风险规则
    "C4",    # 格式化和风格问题
    "F",     # Pyflakes相关规则
    "I",     # 导入相关检查
    "UP",    # Pylint未使用的导入检查
    "B035",  # 不安全的执行调用
    "E101",  # 错误的缩进
    "E111",  # 不正确的缩进
    "E112",  # 预期的缩进块
    "E113",  # 不正确的缩进级别
    "E115",  # 评论的缩进错误
    "E116",  # 不正确的缩进注释
    "E117",  # 不正确的缩进函数定义
    "RUF019", # 特定的 Ruff 规则
    "RUF100", # 文件系统检查
    "RUF101", # 模块级检查
    "S506",  # 安全漏洞检查
    "SIM116", # 重复代码检查
    "SIM401", # 代码简化建议
    "SIM910", # 简化字符串格式
    "W191",  # 禁止混用空格和制表符
    "W605",  # 字符串中的无效转义序列
    "F601",  # 不正确的表达式中断
    "F602",  # 未知的符号
    "F821"   # 未定义名称
]

# 忽略的规则
ignore = [
    "F403",  # 可能的*导入冲突
    "F405",  # 未定义的*导入
    "F841",  # 未使用的局部变量
    "UP007", # 未使用的导入规则
    "UP032", # 未使用的函数或变量
    "B005",  # 循环中的隐式值
    "B006",  # 函数参数中的危险默认值
    "B007",  # 没有显式值的返回
    "B008",  # 不推荐的逻辑表达式
    "B026",  # 不建议的运算符
    "B901",  # 抛出不建议的异常
    "B904",  # 文件操作的改进建议
    "B905"   # 敏感函数调用
]

[format]
indent-style = "space"              # 是否使用空格或制表符进行缩进，制表符-tab、空格-space
docstring-code-format = true        # 是否在注释中格式化代码片段
skip-magic-trailing-comma = true    # 使用现有的尾随逗号作为短行应保持独立的指示
line-ending = "auto"                # 行尾使用的字符
quote-style = "single"              # 字符使用单引号