"""初始化

Revision ID: af13f72ee9ec
Revises: 
Create Date: 2025-05-18 02:07:00.333061

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af13f72ee9ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.run_ddl_script('2025_05_18_0207_ext-hstore_af13f72ee9ec.sql')
    op.run_ddl_script('2025_05_18_0207_ext-pg_trgm_af13f72ee9ec.sql')
    op.run_ddl_script('2025_05_18_0207_ext-unaccent_af13f72ee9ec.sql')
    op.run_ddl_script('2025_05_18_0207_ext-uuid-ossp_af13f72ee9ec.sql')
    op.run_ddl_script('2025_05_18_0207_ext-btree_gin_af13f72ee9ec.sql')
    op.run_ddl_script('2025_05_18_0207_ext-btree_gist_af13f72ee9ec.sql')
    op.run_ddl_script('2025_05_18_0207_ext-fuzzystrmatch_af13f72ee9ec.sql')

    op.run_ddl_script('2025_05_18_0207_tgr_func-update_updated_at_column_af13f72ee9ec.sql')

    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('cellphone', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('state', postgresql.ENUM('disabled', 'enabled', name='user_state_type'), server_default='enabled', nullable=False),
    sa.Column('nickname', sa.String(length=255, collation='zh-x-icu'), nullable=False),
    sa.Column('gender', postgresql.ENUM('male', 'female', 'unknown', name='gender_type'), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cellphone'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('admin_user',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )

    op.run_ddl_script('2025_05_18_0207_tgr-update_updated_at_column_admin_user_af13f72ee9ec.sql')
    op.run_ddl_script('2025_05_18_0207_tgr-update_updated_at_column_users_af13f72ee9ec.sql')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER IF EXISTS tgr_update_updated_at_column ON users;')
    op.execute('DROP TRIGGER IF EXISTS tgr_update_updated_at_column ON admin_user;')

    op.drop_table('admin_user')
    op.drop_table('users')

    op.execute('DROP FUNCTION IF EXISTS update_updated_at_column;')

    postgresql.ENUM(name='user_state_type').drop(op.get_bind())
    postgresql.ENUM(name='gender_type').drop(op.get_bind())

    op.execute('DROP EXTENSION IF EXISTS fuzzystrmatch;')
    op.execute('DROP EXTENSION IF EXISTS btree_gist;')
    op.execute('DROP EXTENSION IF EXISTS btree_gin;')
    op.execute('DROP EXTENSION IF EXISTS "uuid-ossp";')
    op.execute('DROP EXTENSION IF EXISTS unaccent;')
    op.execute('DROP EXTENSION IF EXISTS pg_trgm;')
    op.execute('DROP EXTENSION IF EXISTS hstore;')
    # ### end Alembic commands ###
